version: '3.9'

networks:
  demo:
    driver: bridge

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: technobre/demo-api
    container_name: demo-api
    ports:
      - "8080:8080"
    networks:
      - demo
